version: "2"

services:
  p-heimdall-mongo:
    image: gcr.io/tanigroup-2018/p-heimdall-mongo:latest
    build:
      context: .
      dockerfile: dockerfiles/app.docker
      args:
        - MONGO_ROOT_DB=$MONGO_ROOT_DB
        - MONGO_ROOT_USERNAME=$MONGO_ROOT_USERNAME
        - MONGO_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD
        - MONGO_HOST=$MONGO_HOST
        - MONGO_PORT=$MONGO_PORT
        - LF_MONGO_DB=$LF_MONGO_DB
        - LF_MONGO_USER=$LF_MONGO_USER
        - LF_MONGO_PASS=$LF_MONGO_PASS
    env_file: .env
    container_name: "p-heimdall-mongo"
    working_dir: /usr/src/app
    volumes:
      - mongo_data:/data/db
      - ./init/:/docker-entrypoint-initdb.d/
    ports:
      - "27017:27017"
volumes:
  mongo_data:
